config/routes.rb
Enterpriseape::Application.routes.draw do
  #resources :purchases

  resources :employees

  resources :companies do 
    collection { post :import }
  end

  devise_for :users
  get "welcome/index"
  get "welcome/about"
  get "welcome/contact"
  get "welcome/features"
  get "welcome/faq"
  get "welcome/pricing"

  resources :invoices do
    resources :purchases, except: [:index], controller: 'invoices/purchases'
  end
  
  root to: 'welcome#index'

end

app/models/company.rb
class Company < ActiveRecord::Base
  def self.import(file)
    CSV.foreach(file.path, headers: true) do |row|
      Company.create! row.to_hash
    end
  end

  def self.to_csv
    CSV.generate do |csv|
      csv << column_names
      all.each do |company|
        csv << company.attributes.values_at(*column_names)
      end
    end
  end

end

app/models/employee.rb
class Employee < ActiveRecord::Base
end

app/models/invoice.rb
class Invoice < ActiveRecord::Base
  belongs_to :employee
  has_many :purchases, dependent: :destroy
end

app/models/invoice_search.rb
class InvoiceSearch
  attr_reader :date_from, :date_to

  def initialize(params)
    params ||= {}
    @date_from = parsed_date(params[:date_from], 7.days.ago.to_date.to_s)
    @date_to = parsed_date(params[:date_to], Date.today.next_day.to_s)
  end

  def scope
    #Invoice.where('date BETWEEN ? AND date(?, "+1 day")', @date_from, @date_to)
    #This query works only for sqlite, Possgress runs on the server though >_<
    Invoice.where('date BETWEEN ? AND ?', @date_from, @date_to)
  end

  private #All methods past this point are private.
  
  def parsed_date(date_string, default)
    Date.parse(date_string)
  rescue ArgumentError, TypeError
    default
  end

end

app/models/purchase.rb
class Purchase < ActiveRecord::Base
  belongs_to :invoice
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_action :set_company, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @companies = Company.all
    #respond_with(@companies)

    respond_to do |format|
      format.html
      format.csv { render text: @companies.to_csv }
    end
  end

  def show
    respond_with(@company)
  end

  def new
    @company = Company.new
    respond_with(@company)
  end

  def edit
  end

  def create
    @company = Company.new(company_params)
    @company.save
    respond_with(@company)
  end

  def update
    @company.update(company_params)
    respond_with(@company)
  end

  def destroy
    @company.destroy
    respond_with(@company)
  end

  def import
    Company.import(params[:file])
    redirect_to companies_path, notice: "Companies Added Successfully"
  end

  private
    def set_company
      @company = Company.find(params[:id])
    end

    def company_params
      params.require(:company).permit(:name, :manager, :status, :terms)
    end
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  before_action :set_employee, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @employees = Employee.all
    respond_with(@employees)
  end

  def show
    respond_with(@employee)
  end

  def new
    @employee = Employee.new
    respond_with(@employee)
  end

  def edit
  end

  def create
    @employee = Employee.new(employee_params)
    @employee.save
    respond_with(@employee)
  end

  def update
    @employee.update(employee_params)
    respond_with(@employee)
  end

  def destroy
    @employee.destroy
    respond_with(@employee)
  end

  private
    def set_employee
      @employee = Employee.find(params[:id])
    end

    def employee_params
      params.require(:employee).permit(:name, :phone, :job_type)
    end
end

app/controllers/invoices/purchases_controller.rb
class Invoices::PurchasesController < ApplicationController
  ## Removed per tutorial...not needed?
  #before_action :set_purchase, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @purchases = Purchase.all
    respond_with(@purchases)
  end

  def show
    respond_with(@purchase)
  end

  def new
    @invoice = Invoice.find(params[:invoice_id])
    @purchase = Purchase.new
    respond_with(@purchase)
  end

  def edit
  end

  def create
    @invoice = Invoice.find(params[:invoice_id])
    @purchase = Purchase.new(purchase_params)
    @purchase.invoice = @invoice
    @purchase.save
    respond_with(@invoice)
  end

  def update
    @purchase.update(purchase_params)
    respond_with(@purchase)
  end

  def destroy
    @invoice = Invoice.find(params[:invoice_id])
    @purchase = Purchase.find(params[:id])
    title = @purchase.name

    if @purchase.destroy
      flash[:notice] = "\"#{title}\" was deleted successfully."
      redirect_to @invoice
    else
      flash[:error] = "There was an error deleting the purchase."
      render :show
    end
  end

  private
    def set_purchase
      @purchase = Purchase.find(params[:id])
    end

    def purchase_params
      params.require(:purchase).permit(:name, :category, :quantity, :invoice_id, :price)
    end
end

app/controllers/invoices_controller.rb
class InvoicesController < ApplicationController
  before_action :set_invoice, only: [:show, :edit, :update, :destroy]

  # GET /invoices
  # GET /invoices.json
  def index
    @search = InvoiceSearch.new(params[:search])
    #@invoices = Invoice.all
    @invoices = @search.scope
  end

  # GET /invoices/1
  # GET /invoices/1.json
  def show
    @invoice = Invoice.find(params[:id])
    @purchases = @invoice.purchases
  end

  # GET /invoices/new
  def new
    @invoice = Invoice.new
  end

  # GET /invoices/1/edit
  def edit
  end

  # POST /invoices
  # POST /invoices.json
  def create
    @invoice = Invoice.new(invoice_params)

    respond_to do |format|
      if @invoice.save
        format.html { redirect_to @invoice, notice: 'Invoice was successfully created.' }
        format.json { render action: 'show', status: :created, location: @invoice }
      else
        format.html { render action: 'new' }
        format.json { render json: @invoice.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /invoices/1
  # PATCH/PUT /invoices/1.json
  def update
    respond_to do |format|
      if @invoice.update(invoice_params)
        format.html { redirect_to @invoice, notice: 'Invoice was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @invoice.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /invoices/1
  # DELETE /invoices/1.json
  def destroy
    @invoice.destroy
    respond_to do |format|
      format.html { redirect_to invoices_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_invoice
      @invoice = Invoice.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def invoice_params
      params.require(:invoice).permit(:date, :company, :tax, :employee_id, :status_type)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def about
  end

  def contact
  end

  def features
  end

  def faq
  end

  def pricing
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/helpers/invoices_helper.rb
module InvoicesHelper
end

app/helpers/purchases_helper.rb
module PurchasesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/companies/_form.html.erb
<%= form_for(@company) do |f| %>
  <% if @company.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@company.errors.count, "error") %> prohibited this company from being saved:</h2>

      <ul>
      <% @company.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :manager %><br>
    <%= f.text_field :manager %>
  </div>
  <div class="field">
    <%= f.label :status %><br>
    <%= f.text_field :status %>
  </div>
  <div class="field">
    <%= f.label :terms %><br>
    <%= f.number_field :terms %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/companies/edit.html.erb
<h1>Editing company</h1>

<%= render 'form' %>

<%= link_to 'Show', @company %> |
<%= link_to 'Back', companies_path %>

app/views/companies/index.html.erb
<h1>Listing companies</h1>

<div class="media">
  <div class="media-body">
    <table class="table table-hover">
      <thead>
        <tr>
          <th>Name</th>
          <th>Manager</th>
          <th>Status</th>
          <th>Terms</th>
          <th></th>
          <th></th>
          <th></th>
        </tr>
      </thead>
    
      <tbody>
        <% @companies.each do |company| %>
          <tr>
            <td><%= company.name %></td>
            <td><%= company.manager %></td>
            <td><%= company.status %></td>
            <td><%= company.terms %></td>
            <td><%= link_to 'Show', company %></td>
            <td><%= link_to 'Edit', edit_company_path(company) %></td>
            <td><%= link_to 'Destroy', company, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

<%= link_to 'New Company', new_company_path, class: 'btn btn-default' %>

<br>

<h3>Import Companies</h3>
<%= form_tag import_companies_path, multipart: true do %>
  <%= file_field_tag :file %>
  <%= submit_tag "Upload Companies", class: 'btn btn-default' %>
<% end %>

<h3>Download File</h3>
<%= link_to "Report", companies_path(format: "csv"), class: 'btn btn-default' %>

app/views/companies/new.html.erb
<h1>New company</h1>

<%= render 'form' %>

<%= link_to 'Back', companies_path %>

app/views/companies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @company.name %>
</p>

<p>
  <strong>Manager:</strong>
  <%= @company.manager %>
</p>

<p>
  <strong>Status:</strong>
  <%= @company.status %>
</p>

<p>
  <strong>Terms:</strong>
  <%= @company.terms %>
</p>

<%= link_to 'Edit', edit_company_path(@company) %> |
<%= link_to 'Back', companies_path %>

app/views/employees/_form.html.erb
<%= form_for(@employee) do |f| %>
  <% if @employee.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@employee.errors.count, "error") %> prohibited this employee from being saved:</h2>

      <ul>
      <% @employee.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :phone %><br>
    <%= f.text_field :phone %>
  </div>
  <div class="field">
    <%= f.label :job_type %><br>
    <%= f.text_field :job_type %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/employees/edit.html.erb
<h1>Editing employee</h1>

<%= render 'form' %>

<%= link_to 'Show', @employee %> |
<%= link_to 'Back', employees_path %>

app/views/employees/index.html.erb
<h1>Listing employees</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Phone</th>
      <th>Job type</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @employees.each do |employee| %>
      <tr>
        <td><%= employee.name %></td>
        <td><%= employee.phone %></td>
        <td><%= employee.job_type %></td>
        <td><%= link_to 'Show', employee %></td>
        <td><%= link_to 'Edit', edit_employee_path(employee) %></td>
        <td><%= link_to 'Destroy', employee, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Employee', new_employee_path %>

app/views/employees/new.html.erb
<h1>New employee</h1>

<%= render 'form' %>

<%= link_to 'Back', employees_path %>

app/views/employees/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @employee.name %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @employee.phone %>
</p>

<p>
  <strong>Job type:</strong>
  <%= @employee.job_type %>
</p>

<%= link_to 'Edit', edit_employee_path(@employee) %> |
<%= link_to 'Back', employees_path %>

app/views/invoices/_form.html.erb
<div class="row">
  <%= form_for @invoice, html: { class: 'form-horizontal' } do |f| %>
    <% if @invoice.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@invoice.errors.count, "error") %> prohibited this invoice from being saved:</h2>
  
        <ul>
        <% @invoice.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
  
    <div class="control-group">
      <%= f.label :date, class: 'control-label' %><br>
      <div class="controls">
        <%= f.date_select :date %>
      </div>
    </div>
    <div class="control-group">
      <%= f.label :company, class: 'control-label' %><br>
      <div class="controls">
        <%= f.text_field :company %>
      </div>
    </div>
    <div class="control-group">
      <%= f.label :tax, class: 'control-label' %><br>
      <div class="controls">
        <%= f.text_field :tax %>
      </div>
    </div>
    <div class="control-group">
      <%= f.label :employee_id, class: 'control-label' %>
      <div class="controls">
        <%= collection_select( :invoice, :employee_id, Employee.all, :id, :name, {}, { :multiple => false } ) %>
      </div>
    </div>
    <div class="control-group">
      <%= f.label "Status", class: 'control-label' %>
      <div class="controls">
        <%= f.select(:status_type, options_for_select([['PENDING', 'PENDING'], ['PAID', 'PAID']]), { include_blank: true }) %>
      </div>
    </div>
    <div class="control-group">
      <div class="controls">
        <%= f.submit 'Submit', class: 'btn btn-default' %>
      </div>
    </div>
  <% end %>
</div>

app/views/invoices/edit.html.erb
<h1>Editing invoice</h1>

<%= render 'form' %>

<%= link_to 'Show', @invoice %> |
<%= link_to 'Back', invoices_path %>

app/views/invoices/index.html.erb
<div class="row">
  <h1>Listing invoices</h1>
  <div class="pull-right range-query">
    <%= form_tag invoices_path, method: :get do %>
      <%= text_field_tag 'search[date_from]', @search.date_from %>
      <%= text_field_tag 'search[date_to]', @search.date_to %>
      <%= submit_tag 'Search', class: 'btn search-button' %>
    <% end %>
  </div>
</div>

<div class="media">
  <div class="media-body">
    <table class="table table-hover">
      <thead>
        <tr>
          <th>Date</th>
          <th>Company</th>
          <th>Tax</th>
          <th>Salesperson</th>
          <th>Status</th>
          <th></th>
          <th></th>
          <th></th>
        </tr>
      </thead>
    
      <tbody>
        <% @invoices.each do |invoice| %>
          <tr>
            <td><%= invoice.date.strftime("%Y/%m/%d") %></td>
            <td><%= invoice.company %></td>
            <td><%= invoice.tax %></td>
            <td><%= invoice.employee.name %></td>
            <td><%= invoice.status_type %></td>
            <td><%= link_to 'Show', invoice, class: 'btn btn-mini' %></td>
            <td><%= link_to 'Edit', edit_invoice_path(invoice), class: 'btn btn-mini btn-success' %></td>
            <td><%= link_to 'Delete', invoice, method: :delete, class: 'btn btn-mini btn-danger', data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>


<br>

<%= link_to 'New Invoice', new_invoice_path %>

app/views/invoices/new.html.erb
<h1>New invoice</h1>

<%= render 'form' %>

<%= link_to 'Back', invoices_path %>

app/views/invoices/purchases/_form.html.erb
<%= form_for [@invoice, @purchase] do |f| %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :category %><br>
    <%= f.text_field :category %>
  </div>
  <div class="field">
    <%= f.label :quantity %><br>
    <%= f.number_field :quantity %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/invoices/purchases/edit.html.erb
<h1>Editing purchase</h1>

<%= render 'form' %>

app/views/invoices/purchases/index.html.erb
<h1>Listing purchases</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Category</th>
      <th>Quantity</th>
      <th>Invoice</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @purchases.each do |purchase| %>
      <tr>
        <td><%= purchase.name %></td>
        <td><%= purchase.category %></td>
        <td><%= purchase.quantity %></td>
        <td><%= purchase.invoice %></td>
        <td><%= link_to 'Show', purchase %></td>
        <td><%= link_to 'Edit', edit_purchase_path(purchase) %></td>
        <td><%= link_to 'Destroy', purchase, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Purchase', new_purchase_path %>

app/views/invoices/purchases/new.html.erb
<h1>New purchase</h1>

<%= render 'form' %>

app/views/invoices/purchases/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @purchase.name %>
</p>

<p>
  <strong>Category:</strong>
  <%= @purchase.category %>
</p>

<p>
  <strong>Quantity:</strong>
  <%= @purchase.quantity %>
</p>

<p>
  <strong>Invoice:</strong>
  <%= @purchase.invoice %>
</p>

app/views/invoices/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Date:</strong>
  <%= @invoice.date %>
</p>

<p>
  <strong>Company:</strong>
  <%= @invoice.company %>
</p>

<p>
  <strong>Tax:</strong>
  <%= @invoice.tax %>
</p>

<p>
  <strong>Salesperson:</strong>
  <%= @invoice.employee.name %>
</p>

<div class="media">
  <div class="media-body">
    <table class="table table-hover">
      <thead>
        <tr>
          <th>Name</th>
          <th>Category</th>
          <th>Quantity</th>
          <th>Price</th>
          <th>Total</th>
          <th>Delete</th>
        </tr>
      </thead>
      <tbody>
      <% running_total = 0 %>
      <% @purchases.each do |purchase| %>

        <% if purchase.quantity.nil? %>
          <% purchase.quantity = 0 %>
        <% end %>

        <% if purchase.price.nil? %>
          <% purchase.price = 0 %>
        <% end %>

        <% total = purchase.quantity * purchase.price %>
        <% running_total += total %>

          <tr>
           <td><h4><%= purchase.name %></h4></td>
           <td><h4><%= purchase.category %></h4></td>
           <td><h4><%= purchase.quantity %></h4></td>
           <td><h4><%= number_to_currency(purchase.price) %></h4></td>
           <td><h4><%= number_to_currency(total) %></h4></td>
           <td><h4><%= link_to "Delete", [@invoice, purchase], method: :delete, confirm: "Are you sure you want to delete this purchase?" %></h4></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

<h4 class="pull-right">Invoice total: <%= number_to_currency(running_total) %></h4>

<br><br>

<%= link_to 'Edit', edit_invoice_path(@invoice) %> |
<%= link_to 'Back', invoices_path %>
<%= link_to 'Add new item', new_invoice_purchase_path(@invoice), class: 'pull-right' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Enterpriseape</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="container">
  <ul class="nav nav-tabs">
    <li><%= link_to "Home", root_path %></li>
    <li><%= link_to "About Us", welcome_about_path %></li>
    <li><%= link_to "Contact", welcome_contact_path %></li>
    <li><%= link_to "Features", welcome_features_path %></li>
    <li><%= link_to "FAQs", welcome_faq_path %></li>
    <li><%= link_to "Pricing", welcome_pricing_path %></li>
  
    <% if current_user %>
      <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
      <div class="btn-group pull-right right-nav">
        <button type="button" class="btn btn-mini dropdown-toggle" data-toggle="dropdown">
          <span class="caret"></span>
          <span class="sr-only">Admin</span>
        </button>
        <ul class="dropdown-menu" role="menu">
          <li><%= link_to "Invoices", invoices_path %></li>
          <li><%= link_to "Companies", companies_path %></li>
          <li><%= link_to "Employees(RAW)", employees_path %></li>
      </div>
    <% else %>
      <li><%= link_to "Sign Up", new_user_registration_path %></li>
      <li><%= link_to "Sign In", new_user_session_path %></li>
    <% end %>

  </ul>

  <% if flash[:notice] %>
    <div class="alert alert-success">
      <button type="button" class="close" data-dismiss="alert">&times;</button>
      <%= flash[:notice] %>
    </div>
  <% elsif flash[:alert] %>
    <div class="alert">
      <button type="button" class="close" data-dismiss="alert">&times;</button>
      <%= flash[:alert] %>
    </div>
  <% elsif flash[:error] %>
    <div class="alert alert-error">
      <button type="button" class="close" data-dismiss="alert">&times;</button>
      <%= flash[:error] %>
    </div>
  <% end %>

  <%= yield %>

</div>

</body>
</html>

app/views/welcome/about.html.erb
<h1>Welcome#about</h1>
<p>Find me in app/views/welcome/about.html.erb</p>
<p>BLAH BLAH BLAH BLAH</p>

app/views/welcome/contact.html.erb
<h1>Welcome#contact</h1>
<p>Find me in app/views/welcome/contact.html.erb</p>

app/views/welcome/faq.html.erb
<h1>Welcome#faq</h1>
<p>Find me in app/views/welcome/faq.html.erb</p>

app/views/welcome/features.html.erb
<h1>Welcome#features</h1>
<p>Find me in app/views/welcome/features.html.erb</p>

app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<p>Find me in app/views/welcome/index.html.erb</p>

app/views/welcome/pricing.html.erb
<h1>Welcome#pricing</h1>
<p>Find me in app/views/welcome/pricing.html.erb</p>